name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
    - name: cmake build
      run: cmake .
    - name: cmake make
      run: cmake --build . --target ALL_BUILD
    - name: List Files
      run: Get-ChildItem -Exclude .github,.git,.vs,out,packages,_deps | Get-ChildItem -Recurse
    - name: run Unit Tests
      run: Debug/Libraries.exe
